services:
  web:
    build: .
    image: api-test-image
    container_name: api-test-container
    ports:
      - "8000:80"
    volumes:
      - ../.:/var/www/html
    environment:
      XDEBUG_MODE: debug
      XDEBUG_CLIENT_HOST: host.docker.internal
    extra_hosts:
      - "host.docker.internal:host-gateway"